services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27107"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_secret
